### ISSUE TITLE
Bridge networking possible new configuration requirement

### ISSUE THREAD

**Issue by ClashTheBunny** [ipaqmaster/vfio#10]
I've seen a few places on reddit where the bridge isn't working, and [one place](https://www.reddit.com/r/VFIO/comments/8wz7zw/cant_set_up_network_in_bridged_mode/) seemed to be solved by allowing this with IPTABLES:
```
# iptables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT
```

It's also coroborated with by the [Arch wiki](https://wiki.archlinux.org/title/QEMU#Internal_networking):

> Internal networking
> If you do not give the bridge an IP address and add an iptables rule to drop all traffic to the bridge in the INPUT chain, then the virtual machines will be able to talk to each other, but not to the physical host or to the outside network. This configuration is called internal networking by other virtualization software such as VirtualBox. You will need to either assign static IP addresses to the virtual machines or run a DHCP server on one of them.
> 
> By default iptables would drop packets in the bridge network. You may need to use such iptables rule to allow packets in a bridged network:
> 
> `# iptables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT`

I wonder if this is a new setting by default in linux, or something specific about some default iptables implementations, because some people seem to face it after upgrades.

I don't know how to detect if it's needed, but it seems to be needed in the DHCP case like this script assumes.

By the way, love the script.  Super well engineered and worked like a charm.  Great feedback about what it's going to do with a dry run and what's explicit vs what's implicit.  Thanks so much!

**Comment by ipaqmaster** [comment]
Thank you, I'm glad its been useful at all.

This does seem to be an issue on unique bridge + iptables configurations, I'll look into reproducing the environment and adding that line to the bridge and cleanup sections of the script soon.

**Comment by ipaqmaster** [comment]
Sorry for not coming back to this at the time - it was somewhat difficult to understand the nature of the issue and in the end it sounded more like a local configuration blockade rather than something this script dealt with itself.

The script's custom networking management has been revamped in recent commits.
