### ISSUE TITLE
Parsing of -pci returns Unknown argument

### ISSUE THREAD

**Issue by redeven** [ipaqmaster/vfio#17]
When attempting to do PCI passthrough, specifying anything after `-pci ` will throw `Unknown argument`.

![image](https://github.com/ipaqmaster/vfio/assets/18680184/5c550f4e-65a4-4506-83c8-a09b493dd756)
![image](https://github.com/ipaqmaster/vfio/assets/18680184/f5cdb79e-3fe4-457a-ab55-d761237cf570)

**Comment by ipaqmaster** [comment]
Sorry for the inconvenience - I'm out at the moment I'll fix this tonight. It is most likely just an error in the argument case switch loop.

This also serves as a good reminder for me to set up `bats` tests for testing and tagging commits automatically already.

**Comment by ipaqmaster** [comment]
I think this is now repaired on master. Please let me know.

**Comment by redeven** [comment]
Seems to be working now. Thanks!
