### ISSUE TITLE
path /usr/share/ovmf/x64/OVMF_CODE.fd is wrong

### ISSUE THREAD

**Issue by Marietto2008** [ipaqmaster/vfio#5]
-bios		not specified and couldn't find default '/usr/share/ovmf/x64/OVMF_CODE.fd'. Please install OVMF or set your .fd file with the -bios argument

root@loziomario-Z390-AORUS-PRO:/home/loziomario/Scrivania/new-passT/ipaqmaster# find / -name OVMF_CODE.fd
/usr/share/OVMF/OVMF_CODE.fd

folder /usr/share/ovmf/x64/OVMF_CODE.fd is wrong and should be changed with the new one : /usr/share/OVMF/OVMF_CODE.fd

**Comment by ipaqmaster** [comment]
This script was designed for Archlinux in where that is the correct path. You'll need to use -bios and plug the path in for your OVMF_CODE.fd.

While planned, I haven't added multiple check paths or a dynamic path finding section yet. I may just replace the hard-coded one with something like your find command example or something as more flexible anyway. But I'd probably want to write that to some untracked temporary config file so it doesn't have to run `find` every run and there's probably edge cases to be considered where a plain find run may have multiple results or other problems distro to distro.

For the time being you'll need to use the -bios flag with the path to your OVMF so it continues to run, but making it more dynamic is on my mind.

**Comment by Marietto2008** [comment]
I have the same goal as you and also a project in my mind. maybe we can cooperate. for the moment Im trying to understand how much your method is different from "mine".

**Comment by ipaqmaster** [comment]
A lot of the things you've mentioned are just distribution differences. I'll need to add support for Ubuntu to the script once I have some time.
